config/routes.rb
Rails.application.routes.draw do
  root to: 'things#index'
  resources :things do
    post :update_row_order, on: :collection
  end
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  include RankedModel
  ranks :row_order
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  def index
    @things = Thing.rank(:row_order).all
  end
  def new
    @thing = Thing.new
  end
  def show
    @thing = Thing.find(params[:id])
  end
  def create
    @thing = Thing.create(thing_params)


      if @thing.save
        redirect_to things_path
      else
        render :new
      end

  end

  def update_row_order
    @thing = Thing.find(thing_params[:thing_id])
    @thing.row_order_position = thing_params[:row_order_position]
    @thing.save

    render nothing: true
  end

  private

   def set_thing
     @thing = Thing.find(params[:id])
   end

   def thing_params
     params.require(:thing).permit(:thing_id, :title, :description, :row_order_position)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SortableList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/things/index.html.erb
<div class="panel panel-default">

  <%= link_to 'new', new_thing_path(@thing), :class => 'btn btn-primary pull-left' %>
  <table class="table table-bordered table-striped" id="sortable">
    <thead>
    <tr>
      <th>
        Title
      </th>
      <th>
        Description
      </th>
    </tr>
    </thead>
    <tbody>
    <% @things.each do |thing| %>
        <tr data-item-id=<%= "#{thing.id}" %> class="item">
          <td>
            <%= thing.title %>
          </td>
          <td>
            <%= thing.description %>
          </td>
          <td>
            <%= link_to 'show', thing_path(thing), :class => 'btn btn-default pull-right' %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/things/new.html.erb
<%= form_for(@thing) do |f| %>


    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_area :title %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/things/show.html.erb
<h1></h1>
<div class="panel panel-default">
  <div class="panel-heading">
    <%= @thing.title %>
  </div>
  <div class="panel-body">
    <%= @thing.description %>
  </div>
</div>
<%= link_to 'Back', things_path %>